### ISSUE TITLE
服务端没有语音提示？

### ISSUE THREAD

**Issue by zhjqi111** [StoneMoe/wolf#1]

**Comment by StoneMoe** [comment]
如 README 所述，目前 TTS 功能仅支持 macOS 环境，因其依赖 macOS 自带的`say`命令

如需支持其他环境下的语音播报，可为 utils.say() 函数添加相应的支持，欢迎贡献代码
在彻底完成游戏主逻辑之前，我暂时不会优化 TTS 的平台兼容性

**Comment by StoneMoe** [comment]
related to https://github.com/StoneMoe/wolf/pull/2
